#!/usr/bin/env python3
"""Regenerate the FAQPage JSON-LD on the landing page from the FAQ itself.

    python3 tools/build-faq-schema.py

The schema is derived from the markup rather than written beside it, because a
hand-kept copy is exactly the kind of thing that drifts from the answer a
reader actually sees. Run it after editing the FAQ, before stamp-assets.py.
"""
from __future__ import annotations

import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PAGE = ROOT / "index.html"
START = "  <!-- FAQ schema: generated by tools/build-faq-schema.py -->"
END = "  <!-- /FAQ schema -->"


def text_of(fragment: str) -> str:
    """Readable text from a small HTML fragment, links and emphasis flattened."""
    plain = re.sub(r"<[^>]+>", "", fragment)
    return html.unescape(" ".join(plain.split()))


def main() -> None:
    page = PAGE.read_text(encoding="utf-8")
    faq = page.split('<div class="faq-list', 1)[1]
    entries = []
    for block in re.findall(r"<details>(.*?)</details>", faq, re.S):
        question = re.search(r"<summary>(.*?)</summary>", block, re.S)
        answers = re.findall(r"<p>(.*?)</p>", block, re.S)
        if not question or not answers:
            continue
        entries.append({
            "@type": "Question",
            "name": text_of(question.group(1)),
            "acceptedAnswer": {"@type": "Answer", "text": " ".join(text_of(a) for a in answers)},
        })
    schema = {"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": entries}
    block = (START + '\n  <script type="application/ld+json">\n  '
             + json.dumps(schema, indent=2, ensure_ascii=False).replace("\n", "\n  ")
             + "\n  </script>\n" + END)
    if START in page:
        page = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda _: block, page, flags=re.S)
    else:
        page = page.replace("</head>", block + "\n</head>", 1)
    PAGE.write_text(page, encoding="utf-8")
    print(f"  FAQPage schema: {len(entries)} questions")


if __name__ == "__main__":
    main()
